trigger: 
  branches:
   include:
     - master

pool:
  name: At Home
  
steps:
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 5.3.0'
    inputs:
      versionSpec: 5.3.0

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
      restoreDirectory: '../Packages'
      
  - task: VSBuild@1
    displayName: 'Build solution without Android'
    enabled: false
    inputs:
      solution: 'XamarinDotNetCoreIssue.sln'
      platform: 'any cpu'
      configuration: 'release'

  - task: VSBuild@1
    displayName: 'Build solution including Android'
    inputs:
      solution: 'XamarinDotNetCoreIssueAndroid.sln'
      msbuildArgs: '/restore /p:RestorePackagesPath=../packages'
      platform: 'any cpu'
      configuration: 'release'
      createLogFile: true
      logFileVerbosity: 'diagnostic'