pool:
      vmImage: 'windows-latest'
    steps:

    - task: NuGetToolInstaller@0
      displayName: 'Use NuGet 4.4.1'
      inputs:
        versionSpec: 4.4.1

    - task: NuGetToolInstaller@0
      inputs:
        versionSpec: '5.3.0'
      enabled: false

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'
        restoreDirectory: '../Packages'
        
    - task: VSBuild@1
      displayName: 'Build solution'
      inputs:
        solution: '**/*.sln'
        msbuildArgs: '/p:AppxBundle=Never /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=$(build.artifactstagingdirectory)\Website'
        platform: 'any cpu'
        configuration: 'release'