trigger: 
  branches:
   include:
     - master

pool:
  vmImage: 'windows-latest'
  
steps:
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 5.3.0'
    inputs:
      versionSpec: 5.3.0

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
      restoreDirectory: '../Packages'
      
  - task: VSBuild@1
    displayName: 'Build solution'
    inputs:
      solution: '**/*.sln'
      platform: 'any cpu'
      configuration: 'release'